daemon=1200
syslog=yes
mail=root
pid=/var/run/ddclient.pid
ssl=yes

use=web
web=dynamicdns.park-your-domain.com/getip

protocol=namecheap
server=dynamicdns.park-your-domain.com
login=${DOMAIN}
password=${NAMECHEAP_DDNS_PASSWORD}
${DDNS_HOST}
